### ISSUE TITLE
Failed API request

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/blockscout#1870] opened 2019-05-01 06:11 UTC
https://blockscout.com/eth/kovan/api?module=account&action=tokenlist&address=0x0039F22efB07A647557C7C5d17854CFD6D489eF3

Sometimes it works, sometimes it fails

![image](https://user-images.githubusercontent.com/9360827/57007404-41d49880-6b9d-11e9-9a17-3cb639a9d6f7.png)

**Comment by zachdaniel** [comment] 2019-05-02 15:22
So far I have been unable to reproduce this failure, but given that you're receiving a 504 I would wager that it has something to do with overall node performance and/or an unoptimized query. Have you seen that same failure recently? Were you making a lot of requests to that endpoint when you started seeing failures?

**Comment by vbaranov** [comment] 2019-05-06 15:31
Hey, @rstormsf we updated Kovan instance with [Release 1.3.11](https://github.com/poanetwork/blockscout/releases/tag/v1.3.11-beta) which improved performance on it. Do you still experience failing of `tokenlist` API endpoint?

**Comment by vbaranov** [comment] 2019-05-08 09:06
I will close this one, as we are unable to reproduce this performance issue anymore. @rstormsf reopen it if you will face with this issue again.

**Closed by vbaranov** 2019-05-08 09:06 UTC
Labels: api, performance
