### ISSUE TITLE
Cannot verify a contract code when proxied.

### ISSUE THREAD

**Issue by hickscorp** [poanetwork/blockscout#2839] opened 2019-11-05 19:26 UTC
We're using ZeppelinOS to allow our contracts to be upgradable. The pattern behind it is basically a single proxy that keeps track of the latest version of the real contract code and delegates all the calls to it. In other words, the data segment belongs to the proxy, and the contract code is deployed somewhere else.

It would be really nice to be able to account for this pattern as it's becoming more and more mainstream. While this issue is more like a feature request, please feel free to answer with temporary solution you've found to work with this pattern.

**Comment by vbaranov** [comment] 2019-11-06 12:54
I suppose it is a duplicate of https://github.com/poanetwork/blockscout/issues/1151

**Comment by vbaranov** [comment] 2020-06-17 19:45
@hickscorp I've added decoding of implementation contract calls on proxy contract. For this to be available, both proxy and implementation contracts should be verified. Here is my comment on a related issue. Please let me know if it covers your case. If no, please re-open this issue with providing more details.

**Closed by vbaranov** 2020-06-17 19:45 UTC
Labels: contract verification
