### ISSUE TITLE
ERROR:  database "explorer" does not exist

### ISSUE THREAD

**Issue by wovvan** [poanetwork/blockscout#1259] opened 2018-12-19 14:08 UTC
`2018-12-19 08:42:54.045 UTC [66] ERROR:  database "explorer" does not exist
2018-12-19 08:42:54.045 UTC [66] STATEMENT:  DROP DATABASE "explorer"
2018-12-19 13:29:17.486 UTC [69] ERROR:  canceling statement due to user request
2018-12-19 13:29:17.486 UTC [69] STATEMENT:  UPDATE "blocks" AS b0 SET "consensus" = FALSE, "updated_at" = $1 WHERE (b0."number" = ANY($2)) RETURNING b0."hash", b0."number"
2018-12-19 13:29:17.488 UTC [71] ERROR:  canceling statement due to user request
2018-12-19 13:29:17.488 UTC [71] CONTEXT:  while inserting index tuple (3,48) in relation "addresses"
2018-12-19 13:29:17.488 UTC [71] STATEMENT:  INSERT INTO "addresses" AS a0 ("hash","inserted_at","updated_at") VALUES ($1,$2,$3),($4,$5,$6) ON CONFLICT ("hash") DO UPDATE SET "contract_code" = COALESCE(a0."contract_code", EXCLUDED.contract_code), "fetched_coin_balance" = CASE WHEN EXCLUDED.fetched_coin_balance_block_number IS NOT NULL AND
                  (a0."fetched_coin_balance_block_number" IS NULL OR
                   EXCLUDED.fetched_coin_balance_block_number >= a0."fetched_coin_balance_block_number") THEN
                    EXCLUDED.fetched_coin_balance
             ELSE a0."fetched_coin_balance"
        END
        , "fetched_coin_balance_block_number" = CASE WHEN EXCLUDED.fetched_coin_balance_block_number IS NOT NULL AND
                  (a0."fetched_coin_balance_block_number" IS NULL OR
                   EXCLUDED.fetched_coin_balance_block_number >= a0."fetched_coin_balance_block_number") THEN
                    EXCLUDED.fetched_coin_balance_block_number
             ELSE a0."fetched_coin_balance_block_number"
        END
         RETURNING "updated_at", "inserted_at", "contract_code", "fetched_coin_balance_block_number", "fetched_coin_balance", "hash"`

### Environment

* your dockerfile
* poa node with parity
* mint blocks time 1sec

### Steps to reproduce

when do `make start`

### Actual behaviour

block explorer working slower and slower, but I am not sure this error affects, maybe this issues

**Comment by acravenho** [comment] 2018-12-19 14:13
@wovvan What is the database you're using called?

Are you trying to drop the DB? If so, use `mix do ecto.drop, ecto.create, ecto.migrate` to drop the current DB and create a new one. If you're trying to migrate the current DB use `mix do ecto.create, ecto.migrate`.

**Comment by wovvan** [comment] 2018-12-19 17:08
@acravenho I am using your dockers container. I tried to do `mix do ecto.drop, ecto.create, ecto.migrate` it's does not help.

**Comment by wovvan** [comment] 2018-12-19 17:56
In your makefile we have `migrate: build postgres
	@echo "==> Running migrations"
	@docker run --rm \
					$(BLOCKSCOUT_CONTAINNER_PARAMS) \
					$(DOCKER_IMAGE) /bin/sh -c "echo $$MIX_ENV && mix do ecto.drop --force, ecto.create, ecto.migrate"
`
this create database

**Comment by acravenho** [comment] 2018-12-19 18:04
I'm trying to understand what you're attempting to do. You wrote "block explorer working slower and slower" which implies that you already have it up and running. 

Are you attempting to create a new instance of BlockScout and you received the error above or are you trying to debug why it's running slower?

You're trying to force drop the DB here: `echo $$MIX_ENV && mix do ecto.drop --force, ecto.create, ecto.migrate" `

**Comment by wovvan** [comment] 2018-12-19 18:15
> I'm trying to understand what you're attempting to do. You wrote "block explorer working slower and slower" which implies that you already have it up and running.

I think it is not related this issues. My blockscout responses are growing, and I don't see new blocks after any time, but I see blocks in websockets response. And after several days I catch timeouts. In future I create the issues. I reset webapp to stable version.

**Comment by acravenho** [comment] 2018-12-19 18:17
Yes, that issue is most likely caused by #1243. We have an engineer working on this right now.

**Comment by acravenho** [comment] 2019-01-17 18:54
Closing this issue for now. This has been resolved on our instances.

**Closed by acravenho** 2019-01-17 18:54 UTC
