### ISSUE TITLE
Failed to run indexer

### ISSUE THREAD

**Issue by vaibhavchellani** [poanetwork/blockscout#2097] opened 2019-06-04 14:39 UTC
Running blockscout using docker container, as soon as migration finishes and indexer starts it crashes after emitting several of the logs given below. 
FYI the chain I am connecting to creates blocks in 2 seconds and has `3196197` blocks currently.
```
 Last message: {:continue, {:init, [transport: EthereumJSONRPC.WebSocket, transport_options: %EthereumJSONRPC.WebSocket{url: "ws://3.213.164.228:8546", web_socket: EthereumJSONRPC.WebSocket.WebSocketClient, web_socket_options: %EthereumJSONRPC.WebSocket.WebSocketClient.Options{event: nil, params: nil, web_socket: Indexer.Block.Realtime.WebSocket}}]}}
State: %Indexer.Block.Realtime.Fetcher{block_fetcher: %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "http://3.213.164.22:8545", method_to_url: [eth_getBalance: "http://3.213.164.22:8545", trace_block: "http://3.213.164.22:8545", trace_replayTransaction: "http://3.213.164.22:8545"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], receipts_batch_size: 250, receipts_concurrency: 10}, max_number_seen: nil, previous_number: nil, subscription: nil, timer: nil}
2019-06-04T14:31:02.163 fetcher=block_realtime [error] GenServer Indexer.Block.Realtime.Fetcher terminating
** (ArgumentError) cannot truncate chardata because it contains something that is not valid chardata: %{"code" => -32601, "message" => "Method not found"}
    (logger) lib/logger/utils.ex:78: Logger.Utils.truncate_n/2
    (logger) lib/logger/utils.ex:88: Logger.Utils.truncate_n_list/3
    (logger) lib/logger/utils.ex:48: Logger.Utils.truncate/2
    (logger) lib/logger.ex:692: Logger.__do_log__/3
    (indexer) lib/indexer/block/realtime/fetcher.ex:143: Indexer.Block.Realtime.Fetcher.subscribe_to_new_heads/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:71: Indexer.Block.Realtime.Fetcher.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
```

**Comment by vbaranov** [comment] 2019-06-04 19:37
@vaibhavchellani which Ethereum client endpoint do you use? Geth/Parity or some other?

**Comment by vaibhavchellani** [comment] 2019-06-05 02:27
Parity

**Comment by vbaranov** [comment] 2019-06-05 08:58
@vaibhavchellani which version of Parity client? the latest stable one?

**Comment by vaibhavchellani** [comment] 2019-06-05 09:47
We are using `version Parity-Ethereum/v2.4.5-stable-76d4064-20190408/x86_64-linux-gnu/rustc1.33.0`

**Comment by vbaranov** [comment] 2019-06-05 09:56
Did you start Parity in archive mode?

**Comment by vaibhavchellani** [comment] 2019-06-05 10:36
Yes we have the following config for footprint in our config.toml file. 
```
[footprint]
tracing = "on"
pruning = "archive"
fat_db = "on"
```

**Comment by vaibhavchellani** [comment] 2019-06-06 18:30
>does it still crash if to restart docker container?

Yes it does. 

>If I understand correctly it stuck on a definite block. Is this correct?


I am not sure, I don't understand what logs are indicating.

> If so, could you provide block's content from your chain 

I can provide you with the block details, but I am not sure which block number should I fetch for? Do you have any ideas on what exactly I can provide more details

**Comment by vbaranov** [comment] 2019-06-07 09:56
I am not sure what is going on with indexing chain, because there are not so many details about the chain you are trying to index. Please provide all details to reproduce it: toml/spec or public endpoints of the chain if so.

**Comment by vbaranov** [comment] 2019-06-07 12:02
@vaibhavchellani try to compile blockscout from this branch https://github.com/poanetwork/blockscout/pull/2119. It could fix your problem.

**Comment by vbaranov** [comment] 2019-06-11 12:57
@vaibhavchellani ☝️ did it help in your case?

**Comment by vaibhavchellani** [comment] 2019-06-11 17:20
@vbaranov I'll build and let you know, checking it out, thanks for the help!

**Comment by vbaranov** [comment] 2019-06-20 11:11
@vaibhavchellani I am closing this. Please reopen if the issue still exists.

**Closed by vbaranov** 2019-06-20 11:11 UTC
Labels: waiting on feedback
