### ISSUE TITLE
Pagination button is not showing up on the address page

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#588] opened 2018-08-22 18:25 UTC
I've only noticed this bug on one particular page: https://core-alpha.poaexplorer.com/en/addresses/0xef5d6a39ed285a9299c679fd2863bc28bb2f1106/transactions

This address has over 1,300 transactions but the pagination button is not appearing. It is also not hidden by CSS.

### Environment

* Operating System: Linux

### Steps to reproduce

1. Visit https://core-alpha.poaexplorer.com/en/addresses/0xef5d6a39ed285a9299c679fd2863bc28bb2f1106/transactions
2. Scroll to the bottom of the page.
3. There should a next page button.

**Comment by jimmay5469** [comment] 2018-08-28 12:14
@acravenho I'm actually seeing the "Older" button when I visit. Is it still not showing for you?

**Comment by jimmay5469** [comment] 2018-08-28 12:17
It looks like it shows on the first page but after I click it once I don't see it on the second page...

**Comment by jimmay5469** [comment] 2018-08-28 12:25
I am unable to reproduce on `master` (`39bd00b9`)...

**Comment by arthurra** [comment] 2018-10-03 14:12
I'm also unable to reproduce on `master`. Closing this issue...

**Closed by arthurra** 2018-10-03 14:12 UTC
Labels: bug, priority: high, team: contributor
