### ISSUE TITLE
Internal server error when on the [Blocks Validated] tab of miners

### ISSUE THREAD

**Issue by hadv** [poanetwork/blockscout#1524] opened 2019-03-05 05:40 UTC
Internal server error when on the [Blocks Validated] tab of miner on Sokol testnet explorer. And I face the same error on my private PoA network.

![image](https://user-images.githubusercontent.com/941411/53783140-02921e80-3f43-11e9-8f69-f2b4b1732043.png)

### Environment

Current version of PoA Sokol testnet
https://blockscout.com/poa/sokol

### Steps to reproduce

1. Click on any miner address
2.Click on [Blocks Validated] tab

### Expected behaviour

Show all the blocks mined/sealed by the selected miner

### Actual behaviour

internal server error

```
Request: GET /address/0x3f9fc72f6992c64db93815c7eadcdbccf4d332d7/validations
** (exit) an exception was raised:
    ** (ArgumentError) assign @coin_balance_status not available in eex template.

Please make sure all proper assigns have been set. If this
is a child template, ensure assigns are given explicitly by
the parent template as they are not automatically forwarded.

Available assigns: [:address, :conn, :current_path, :exchange_rate, :transaction_count, :validation_count, :view_module, :view_template]

        (phoenix_html) lib/phoenix_html/engine.ex:132: Phoenix.HTML.Engine.fetch_assign!/2
        (block_scout_web) lib/block_scout_web/templates/address/overview.html.eex:77: BlockScoutWeb.AddressView."overview.html"/1
        (block_scout_web) lib/block_scout_web/templates/address_validation/index.html.eex:2: BlockScoutWeb.AddressValidationView."index.html"/1
        (block_scout_web) lib/block_scout_web/templates/layout/app.html.eex:39: BlockScoutWeb.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:399: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:729: Phoenix.Controller.__put_render__/5
        (block_scout_web) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/controller.ex:746: Phoenix.Controller.instrument_render_and_send/4
```

**Comment by vbaranov** [comment] 2019-03-05 06:29
Thanks for the report. The issue is with `v1.3.3`. It has been fixed in the `v1.3.4`. We plan to upgrade Sokol up to `v1.3.4` https://github.com/poanetwork/blockscout/issues/1514 soon.

**Comment by hadv** [comment] 2019-03-06 04:24
@vbaranov it might be not related to the issue. When I upgrade from `1.3.3` to `1.3.4` then I have to re-verify smart contract code. Do you have any idea that It's wrong somewhere from me? Or what I need to do when upgrading and still reserve all the old data.

**Comment by vbaranov** [comment] 2019-03-06 12:27
@hadv from my perspective it can be if you dropped the `smart-contracts` table or removed the row related to your verified smart-contract. Btw, all Blockscout instances have been updated to `v1.3.4`. If you will see the same behaviour there, please let us know.

**Closed by vbaranov** 2019-03-06 12:27 UTC
Labels: bug :bug:, chain: SOK :chains:
