### ISSUE TITLE
Can't verify contract

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/blockscout#1884] opened 2019-05-03 10:14 UTC
https://blockscout.com/poa/core/address/0x8dc4f704a5fdf9f09ed561381bd02187201a83b8/contract_verifications

![image](https://user-images.githubusercontent.com/9360827/57131508-71c49d00-6d51-11e9-9c1d-dcc4b2926a4a.png)

it's the same as 
https://etherscan.io/address/0xfab46e002bbf0b4509813474841e0716e6730136#code

0.5.5 compiler

there are no constructor args
```js
contract FaucetToken is ERC20, ERC20Detailed, ERC20Mintable, ERC20Burnable {
    uint8 public constant DECIMALS = 18;
    uint256 public constant INITIAL_SUPPLY = 10000 * (10 ** uint256(DECIMALS));

    /**
     * @dev Constructor that gives msg.sender all of existing tokens.
     */
    constructor () public ERC20Detailed("FaucetToken", "FAU", DECIMALS) {
    }
```

**Comment by dileepfrog** [comment] 2019-05-03 16:23
Experiencing the same issue for contracts with and without constructor arguments, a possible dupe of issue https://github.com/poanetwork/blockscout/issues/1786

**Comment by eduardonunesp** [comment] 2019-05-03 18:16
Here my contract isn't compile too, when I look in console there a message log

```2019-05-03T15:14:22.557 application=plug request_id=2mdjtq0cub2p0nf728007qp2 [info] POST /address/0x2ec08d124393b0641638844536d8b6d82b9953a8/contract_verifications
/Users/eddie/Sandbox/blockscout/apps/explorer/priv/compile_solc.js:46
    const response = output.contracts[newContractName] || output.contracts['']
                                     ^

TypeError: Cannot read property 'New.sol' of undefined
    at /Users/eddie/Sandbox/blockscout/apps/explorer/priv/compile_solc.js:46:38
    at IncomingMessage.<anonymous> (/Users/eddie/Sandbox/blockscout/apps/explorer/node_modules/solc/wrapper.js:247:13)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
2019-05-03T15:14:26.667 application=plug request_id=2mdjtq0cub2p0nf728007qp2 [info] Sent 200 in 4110ms```

**Comment by ayrat555** [comment] 2019-05-07 08:31
@rstormsf issue will be fixed with https://github.com/poanetwork/blockscout/pull/1898

@eduardonunesp you're experiencing issue not related to this. I think you provided wrong solidity version or evm version. Can you please create a new issue describing all parameters that you passed

**Comment by vbaranov** [comment] 2019-05-08 08:49
@ayrat555 we shouldn't close it until update has not been installed to affected chain

**Comment by ayrat555** [comment] 2019-05-08 09:44
@vbaranov agreed. it was closed automatically

**Comment by vbaranov** [comment] 2019-05-23 18:25
@rstormsf  https://blockscout.com/poa/core/address/0x8dc4f704a5fdf9f09ed561381bd02187201a83b8/contracts

Fix deployed to the instance

**Closed by vbaranov** 2019-05-23 18:25 UTC
Labels: bug :bug:, contract verification, contracts
