### ISSUE TITLE
Failed to open smart-contract page: no function clause matching in BlockScoutWeb.AddressView.from_address_hash/1

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#1503] opened 2019-02-28 17:21 UTC
### Details

Failed to open smart-contract's page

Chain: **Goerli**
Smart-contract address: `0x4e10a95f0bb2fec6ec1c4296a16420a018a5f9fe`
Link to the page: https://blockscout.com/eth/goerli/address/0x4e10a95f0bb2fec6ec1c4296a16420a018a5f9fe/transactions

Some contracts do not have a `contracts_creation_internal_transaction` or a `contracts_creation_transaction`, but at least one of those should be populated in all cases

##Logs

```
Request: GET /address/0x4e10a95f0bb2fec6ec1c4296a16420a018a5f9fe/transactions
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in BlockScoutWeb.AddressView.from_address_hash/1
        (block_scout_web) lib/block_scout_web/views/address_view.ex:224: BlockScoutWeb.AddressView.from_address_hash(%Explorer.Chain.Address{__meta__: #Ecto.Schema.Metadata<:loaded, "addresses">, contract_code: %Explorer.Chain.Data{bytes: <<96, 128, 96, 64, 82, 96, 4, 54, 16, 97, 0, 196, 87, 99, 255, 255, 255, 255, 124, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>}, contracts_creation_internal_transaction: nil, contracts_creation_transaction: nil, fetched_coin_balance: #Explorer.Chain.Wei<0>, fetched_coin_balance_block_number: 158778, hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<78, 16, 169, 95, 11, 178, 254, 198, 236, 28, 66, 150, 161, 100, 32, 160, 24, 165, 249, 254>>}, inserted_at: #DateTime<2019-02-11 16:51:31.162300Z>, names: [], nonce: nil, smart_contract: nil, token: nil, updated_at: #DateTime<2019-02-11 16:51:31.162300Z>})
        (block_scout_web) lib/block_scout_web/templates/address/overview.html.eex:60: BlockScoutWeb.AddressView."overview.html"/1
        (block_scout_web) lib/block_scout_web/templates/address_transaction/index.html.eex:3: BlockScoutWeb.AddressTransactionView."index.html"/1
        (block_scout_web) lib/block_scout_web/templates/layout/app.html.eex:39: BlockScoutWeb.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:399: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:729: Phoenix.Controller.__put_render__/5
        (block_scout_web) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/controller.ex:746: Phoenix.Controller.instrument_render_and_send/4
```

**Comment by zachdaniel** [comment] 2019-03-05 16:03
Lets see how many addresses are affected. I *think* this query should get us a list of addresses like this. We should see if its isolated to Goerli or if its happening on other chains as well. Can you run this query on the relevant databases to see what we find?

```
SELECT COUNT(DISTINCT (addresses.hash))
FROM addresses
WHERE addresses.contract_code IS NOT NULL
  AND (
    NOT EXISTS(
        SELECT hash FROM internal_transactions WHERE transaction_hash = created_contract_address_hash
      ) OR
    NOT EXISTS(
        SELECT hash FROM transactions WHERE hash = created_contract_address_hash
      )
  );
```

You can `SELECT encode(addresses.hash, 'hex')` to get some address hashes to confirm this behavior with as well.

**Comment by zachdaniel** [comment] 2019-03-05 22:04
There are `50581` contracts with this same affliction in the stg database, from what I can tell. I'm going to investigate more of them in the morning to see if I can identify a cause. With that in mind I'm going to:

1.) clean it up to still render the page but show a nice error message 
2.) write a task that finds and fixes these addresses
3.) identify the cause and resolve the issue at the source.

**Comment by zachdaniel** [comment] 2019-03-14 13:52
This issue will be fully resolved once #1543 is merged.

**Comment by goodsoft** [comment] 2019-03-14 13:56
I'd wait until we fully synchronize before closing.

**Comment by zachdaniel** [comment] 2019-03-14 13:56
Yeah, agreed :+1:

**Comment by zachdaniel** [comment] 2019-04-04 15:11
This has been dealt with by adding a nicer error message in #1534, and by resolving the underlying data issue in #1543.

**Closed by zachdaniel** 2019-04-04 15:11 UTC
Labels: BlockScout, bug :bug:, contracts, internal txs indexing, severity: 1 :boom:, team: architecture

**Comment by vbaranov** [comment] 2019-04-12 18:54
@zachdaniel is the way to fix `undetermined contract creator` for old blocks, that we issued before introducing of new indexing scheme in #1543 for geth-based chains?

**Comment by zachdaniel** [comment] 2019-04-12 20:43
Do geth based chains support that kind of request?

**Comment by zachdaniel** [comment] 2019-04-12 20:44
It looks like they do.
