### ISSUE TITLE
Verify Contract RPC Endpoint Not Working

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1775] opened 2019-04-18 00:03 UTC
I've been attempting to verify contracts through the RPC endpoint but have not been successful. Below I've provided a few examples.

Etherscan Source Code: https://etherscan.io/address/0x1b528346f0631dc465813a757eaf38035b44b9e4#code

Request URL: 

```
https://blockscout.com/eth/mainnet/api?module=contract&action=verify&addressHash=0x1b528346f0631dc465813a757eaf38035b44b9e4&name=KCBToken&compilerVersion=v0.4.18+commit.9cf6e910&optimization=false&contractSourceCode=pragma solidity ^0.4.18;  // ---------------------------------------------------------------------------- // ‘KCB Token' token contract KCB智能合约 //Made By 吴航 // Deployed to : 0x743fd6d924ae32ccddb377f11d43129cdd0d0d00 // Symbol      : KCB // Name        : KCB Token // Total supply: 1000000000 // Decimals    : 18 // // Enjoy. // // (c) by Hang Wu on behalf of the Ming Organization. transferAnyERC20Token // ----------------------------------------------------------------------------   // ---------------------------------------------------------------------------- // Safe maths // ---------------------------------------------------------------------------- contract SafeMath {     function safeAdd(uint a, uint b) public pure returns (uint c) {         c = a + b;         require(c >= a);     }     function safeSub(uint a, uint b) public pure returns (uint c) {         require(b <= a);         c = a - b;     }     function safeMul(uint a, uint b) public pure returns (uint c) {         c = a * b;         require(a == 0 || c / a == b);     }     function safeDiv(uint a, uint b) public pure returns (uint c) {         require(b > 0);         c = a / b;     } }   // ---------------------------------------------------------------------------- // ERC Token Standard #20 Interface // https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20-token-standard.md // ---------------------------------------------------------------------------- contract ERC20Interface {     function totalSupply() public constant returns (uint);     function balanceOf(address tokenOwner) public constant returns (uint balance);     function allowance(address tokenOwner, address spender) public constant returns (uint remaining);     function transfer(address to, uint tokens) public returns (bool success);     function approve(address spender, uint tokens) public returns (bool success);     function transferFrom(address from, address to, uint tokens) public returns (bool success);      event Transfer(address indexed from, address indexed to, uint tokens);     event Approval(address indexed tokenOwner, address indexed spender, uint tokens); }   // ---------------------------------------------------------------------------- // Contract function to receive approval and execute function in one call // // Borrowed from MiniMeToken // ---------------------------------------------------------------------------- contract ApproveAndCallFallBack {     function receiveApproval(address from, uint256 tokens, address token, bytes data) public; }   // ---------------------------------------------------------------------------- // Owned contract // ---------------------------------------------------------------------------- contract Owned {     address public owner;     address public newOwner;      event OwnershipTransferred(address indexed _from, address indexed _to);      function Owned() public {         owner = msg.sender;     }      modifier onlyOwner {         require(msg.sender == owner);         _;     }      function transferOwnership(address _newOwner) public onlyOwner {         newOwner = _newOwner;     }     function acceptOwnership() public {         require(msg.sender == newOwner);         OwnershipTransferred(owner, newOwner);         owner = newOwner;         newOwner = address(0);     } }   // ---------------------------------------------------------------------------- // ERC20 Token, with the addition of symbol, name and decimals and assisted // token transfers // ---------------------------------------------------------------------------- contract KCBToken is ERC20Interface, Owned, SafeMath {     string public symbol;     string public  name;     uint8 public decimals;     uint public _totalSupply;      mapping(address => uint) balances;     mapping(address => mapping(address => uint)) allowed;       // ------------------------------------------------------------------------     // Constructor     // ------------------------------------------------------------------------     function KCBToken() public {         symbol = "KCB";         name = "Keenly Change Bitcoin";         decimals = 18;         _totalSupply = 1000000000e18; //十亿代币         balances[0x743fd6d924ae32ccddb377f11d43129cdd0d0d00] = _totalSupply;         Transfer(address(0), 0x743fd6d924ae32ccddb377f11d43129cdd0d0d00, _totalSupply);     }       // ------------------------------------------------------------------------     // Total supply     // ------------------------------------------------------------------------     function totalSupply() public constant returns (uint) {         return _totalSupply  - balances[address(0)];     }       // ------------------------------------------------------------------------     // Get the token balance for account tokenOwner     // ------------------------------------------------------------------------     function balanceOf(address tokenOwner) public constant returns (uint balance) {         return balances[tokenOwner];     }       // ------------------------------------------------------------------------     // Transfer the balance from token owner's account to to account     // - Owner's account must have sufficient balance to transfer     // - 0 value transfers are allowed     // ------------------------------------------------------------------------     function transfer(address to, uint tokens) public returns (bool success) {         balances[msg.sender] = safeSub(balances[msg.sender], tokens);         balances[to] = safeAdd(balances[to], tokens);         Transfer(msg.sender, to, tokens);         return true;     }       // ------------------------------------------------------------------------     // Token owner can approve for spender to transferFrom(...) tokens     // from the token owner's account     //     // https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20-token-standard.md     // recommends that there are no checks for the approval double-spend attack     // as this should be implemented in user interfaces     // ------------------------------------------------------------------------     function approve(address spender, uint tokens) public returns (bool success) {         allowed[msg.sender][spender] = tokens;         Approval(msg.sender, spender, tokens);         return true;     }       // ------------------------------------------------------------------------     // Transfer tokens from the from account to the to account     //     // The calling account must already have sufficient tokens approve(...)-d     // for spending from the from account and     // - From account must have sufficient balance to transfer     // - Spender must have sufficient allowance to transfer     // - 0 value transfers are allowed     // ------------------------------------------------------------------------     function transferFrom(address from, address to, uint tokens) public returns (bool success) {         balances[from] = safeSub(balances[from], tokens);         allowed[from][msg.sender] = safeSub(allowed[from][msg.sender], tokens);         balances[to] = safeAdd(balances[to], tokens);         Transfer(from, to, tokens);         return true;     }       // ------------------------------------------------------------------------     // Returns the amount of tokens approved by the owner that can be     // transferred to the spender's account     // ------------------------------------------------------------------------     function allowance(address tokenOwner, address spender) public constant returns (uint remaining) {         return allowed[tokenOwner][spender];     }       // ------------------------------------------------------------------------     // Token owner can approve for spender to transferFrom(...) tokens     // from the token owner's account. The spender contract function     // receiveApproval(...) is then executed     // ------------------------------------------------------------------------     function approveAndCall(address spender, uint tokens, bytes data) public returns (bool success) {         allowed[msg.sender][spender] = tokens;         Approval(msg.sender, spender, tokens);         ApproveAndCallFallBack(spender).receiveApproval(msg.sender, tokens, this, data);         return true;     }       // ------------------------------------------------------------------------     // Don't accept ETH     // ------------------------------------------------------------------------     function () public payable {         revert();     }       // ------------------------------------------------------------------------     // Owner can transfer out any accidentally sent ERC20 tokens     // ------------------------------------------------------------------------     function transferAnyERC20Token(address tokenAddress, uint tokens) public onlyOwner returns (bool success) {         return ERC20Interface(tokenAddress).transfer(owner, tokens);     } }
```

## Another Example
Etherscan Source Code:
https://etherscan.io/address/0x3644ab79a793244abdbca44189a01756042db2e3#code

Request URL:

```
https://blockscout.com/eth/mainnet/api?module=contract&action=verify&addressHash=0x3644ab79a793244abdbca44189a01756042db2e3&name=againstRelease&compilerVersion=v0.4.24+commit.e67f0147&optimization=true&contractSourceCode=pragma solidity >= 0.4.24;

interface token {
    function transfer(address receiver, uint amount) external;
    function balanceOf(address tokenOwner) constant external returns (uint balance);
}

contract againstRelease {
    string public  name = "AGAINST Release";
    string public symbol = "AGAINST Release";
    string public comment = 'AGAINST Release Contract';
    token public tokenReward = token(0xF7Be133620a7D944595683cE2B14156591EFe609);
    address releaseWallet = address(0x4e0871dC93410305F83aEEB15741B2BDb54C3c5a);
    event FundTransfer(address backer, uint amount, bool isContribution);

    function () payable external {
        uint stockSupply = tokenReward.balanceOf(address(this));
        require(stockSupply >= 1000000*(10**18),"Release Ended");
        require(msg.value >= 1*(10**14),"Very low bid");
        tokenReward.transfer(msg.sender, 1000000*(10**18));
		uint amount = address(this).balance;
        if (amount > 2*(10**15)) {
            if (releaseWallet.send(amount)) {
			  emit FundTransfer(releaseWallet, amount, false);
			}
        }
    }
}
```

Curl Request:

```
curl -X GET "https://blockscout.com/eth/mainnet/api?module=contract&action=verify&addressHash=0x3644ab79a793244abdbca44189a01756042db2e3&name=againstRelease&compilerVersion=v0.4.24+commit.e67f0147&optimization=true&contractSourceCode=pragma solidity >= 0.4.24;  interface token {     function transfer(address receiver, uint amount) external;     function balanceOf(address tokenOwner) constant external returns (uint balance); }  contract againstRelease {     string public  name = "AGAINST Release";     string public symbol = "AGAINST Release";     string public comment = 'AGAINST Release Contract';     token public tokenReward = token(0xF7Be133620a7D944595683cE2B14156591EFe609);     address releaseWallet = address(0x4e0871dC93410305F83aEEB15741B2BDb54C3c5a);     event FundTransfer(address backer, uint amount, bool isContribution); 	     function () payable external {                 uint stockSupply = tokenReward.balanceOf(address(this));          require(stockSupply >= 1000000*(10**18),"Release Ended");         require(msg.value >= 1*(10**14),"Very low bid");         tokenReward.transfer(msg.sender, 1000000*(10**18)); 		uint amount = address(this).balance;         if (amount > 2*(10**15)) {             if (releaseWallet.send(amount)) { 			  emit FundTransfer(releaseWallet, amount, false); 			}         }     			     } }" -H "accept: application/json"
```

### Steps to reproduce

1. Take any smart contract verified on Etherscan.io and attempt to use the `contract` module, `verify` action to verify a  contract on BlockScout.

2. I've received `Internal Server Errors` as well as `Something went wrong while publishing the contract.`

### Expected behaviour

Verify the contract

### Actual behaviour

Internal Server Errors and other errors

**Comment by zachdaniel** [comment] 2019-04-18 03:21
I’ll look into this first thing in the morning!

**Comment by acravenho** [comment] 2019-04-18 03:51
Thanks @zachdaniel 👍

**Comment by zachdaniel** [comment] 2019-04-18 14:55
I just hit the URL you provided and it appears to have worked. I didn't use `curl` though, could it perhaps be an encoding issue with curl?

**Comment by zachdaniel** [comment] 2019-04-18 14:59
Okay, so the first example didn't work, but the second one did.

**Comment by zachdaniel** [comment] 2019-04-18 15:26
Update:
```
node apps/explorer/priv/compile_solc.js $code "v0.4.18+commit.9cf6e910" "0" "200" "KCBToken" "{}" "petersburg"
```

Returns "undefined" on my machine currently :/

**Comment by acravenho** [comment] 2019-04-18 18:08
Hey Zach, 

Using the URLs above I wasn't able to get any other message than `Something went wrong while publishing the contract.`

Please let me know if you need more examples.

**Comment by zachdaniel** [comment] 2019-04-18 18:18
I verified the second example using the API and I got a successful response and it shows as verified in the UI: https://blockscout.com/eth/mainnet/address/0x3644ab79a793244abdbca44189a01756042db2e3/contracts

**Comment by acravenho** [comment] 2019-04-18 18:22
Can you provide an example of using the API endpoint. I've tried 100 contracts in a row now and all have failed?

**Comment by zachdaniel** [comment] 2019-04-18 18:25
Its kind of a black box, so it is difficult to determine what is causing it to have no output. The `solcSnapshot.compile` is just not returning a contract for some reason.

**Comment by zachdaniel** [comment] 2019-04-18 18:26
As for the API, I just used an HTTP request tool (Insomnia, similar to postman) to send a get request to the URL you provided.

`https://blockscout.com/eth/mainnet/api?module=contract&action=verify&addressHash=0x3644ab79a793244abdbca44189a01756042db2e3&name=againstRelease&compilerVersion=v0.4.24+commit.e67f0147&optimization=true&contractSourceCode=pragma solidity >= 0.4.24;  interface token {     function transfer(address receiver, uint amount) external;     function balanceOf(address tokenOwner) constant external returns (uint balance); }  contract againstRelease {     string public  name = "AGAINST Release";     string public symbol = "AGAINST Release";     string public comment = 'AGAINST Release Contract';     token public tokenReward = token(0xF7Be133620a7D944595683cE2B14156591EFe609);     address releaseWallet = address(0x4e0871dC93410305F83aEEB15741B2BDb54C3c5a);     event FundTransfer(address backer, uint amount, bool isContribution); 	     function () payable external {                 uint stockSupply = tokenReward.balanceOf(address(this));          require(stockSupply >= 1000000*(10**18),"Release Ended");         require(msg.value >= 1*(10**14),"Very low bid");         tokenReward.transfer(msg.sender, 1000000*(10**18)); 		uint amount = address(this).balance;         if (amount > 2*(10**15)) {             if (releaseWallet.send(amount)) { 			  emit FundTransfer(releaseWallet, amount, false); 			}         }     			     } }`

This is the response I got:
```
{
  "status": "1",
  "result": {
    "SourceCode": "pragma solidity >= 0.4.24;  interface token {     function transfer(address receiver, uint amount) external;     function balanceOf(address tokenOwner) constant external returns (uint balance); }  contract againstRelease {     string public  name = \"AGAINST Release\";     string public symbol = \"AGAINST Release\";     string public comment = 'AGAINST Release Contract';     token public tokenReward = token(0xF7Be133620a7D944595683cE2B14156591EFe609);     address releaseWallet = address(0x4e0871dC93410305F83aEEB15741B2BDb54C3c5a);     event FundTransfer(address backer, uint amount, bool isContribution); \t     function () payable external {                 uint stockSupply = tokenReward.balanceOf(address(this));          require(stockSupply >= 1000000*(10**18),\"Release Ended\");         require(msg.value >= 1*(10**14),\"Very low bid\");         tokenReward.transfer(msg.sender, 1000000*(10**18)); \t\tuint amount = address(this).balance;         if (amount > 2*(10**15)) {             if (releaseWallet.send(amount)) { \t\t\t  emit FundTransfer(releaseWallet, amount, false); \t\t\t}         }     \t\t\t     } }",
    "OptimizationUsed": "1",
    "DecompilerVersion": "",
    "DecompiledSourceCode": "Contract source code not decompiled.",
    "ContractName": "againstRelease",
    "CompilerVersion": "v0.4.24+commit.e67f0147",
    "Address": "0x3644ab79a793244abdbca44189a01756042db2e3",
    "ABI": "[{\"constant\":true,\"inputs\":[],\"name\":\"name\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"},{\"constant\":true,\"inputs\":[],\"name\":\"tokenReward\",\"outputs\":[{\"name\":\"\",\"type\":\"address\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"},{\"constant\":true,\"inputs\":[],\"name\":\"symbol\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"},{\"constant\":true,\"inputs\":[],\"name\":\"comment\",\"outputs\":[{\"name\":\"\",\"type\":\"string\"}],\"payable\":false,\"stateMutability\":\"view\",\"type\":\"function\"},{\"payable\":true,\"stateMutability\":\"payable\",\"type\":\"fallback\"},{\"anonymous\":false,\"inputs\":[{\"indexed\":false,\"name\":\"backer\",\"type\":\"address\"},{\"indexed\":false,\"name\":\"amount\",\"type\":\"uint256\"},{\"indexed\":false,\"name\":\"isContribution\",\"type\":\"bool\"}],\"name\":\"FundTransfer\",\"type\":\"event\"}]"
  },
  "message": "OK"
}
```

**Comment by zachdaniel** [comment] 2019-04-18 19:15
I don't know if I'm just on an old verison of `curl` or what but I cannot get curl to play nicely with the brackets in the URL no matter what I do.

**Comment by acravenho** [comment] 2019-04-18 19:16
I feel like `POST` might be such a better solution here.

**Comment by zachdaniel** [comment] 2019-04-18 19:18
Yeah, you're probably right. I hooked it up as part of the JSON RPC since that was already set up and would be documented though. I can change it to a POST and just handle it in a one off controller if necessary though.

**Comment by zachdaniel** [comment] 2019-04-22 18:18
Still trying to figure out what is going on here. Its definitely unrelated to the web application itself, and only related to what is being passed into the script. At the very least, I've added an endpoint to verify contracts with a POST request.

**Comment by zachdaniel** [comment] 2019-04-22 20:20
@acravenho I saw that there were some other issues with contract verification using the UI, I'm wondering if that may give us any insight into this issue. Are contracts correctly being verified via the UI but then failing via the API?

**Comment by acravenho** [comment] 2019-04-22 20:45
I can give the API a try again once the PR is deployed to production. I'll keep track of which contracts failed the API but were successful in the UI.

**Comment by zachdaniel** [comment] 2019-04-24 20:21
@acravenho We deployed the new POST endpoint to stg. Info on it can be found in the PR #1806

**Comment by acravenho** [comment] 2019-04-25 01:51
Thanks Zach. I saw the deployment issue for ETH Mainnet and have been waiting for a few of these issues to be deployed to production. I might test some of these on staging and will let you know if I encounter any problems 👍

**Comment by chebykin** [comment] 2019-04-29 23:18
I tried to verify a contract using my own blockscout installation (v1.3.11-beta) and a private chain but stuck with the same problem as described here.

Compiler messages were cut by JSON.stringify, I made this PR #1863

With this hack https://github.com/chebykin/blockscout/commit/fc03f50788f892f82f30a41c504bef2767e8dc8f  I was able to receive this error using POST API:  `{"contract_source_code":"Wrong contract name, please try again."}`.
But the compiler error was ` "Error retrieving binary: Not Found`

The following arguments was passed into `compile_solc.js`:
`
["/usr/bin/node","/home/ubuntu/blockscout/_build/prod/lib/explorer/priv/compile_solc.js","pragma solidity 0.5.7; contract MyContractStorage { mapping(bytes32 => address) public contracts; function se     tContract(bytes32 _key, address _value) external {contracts[_key] = _value;}}","0.5.7+commit.6da8b019","0","200","New.sol","{}","byzantium"]
`

Hope this information can help. Eager to see this in production 😊

**Comment by zachdaniel** [comment] 2019-04-30 15:50
@chebykin According to the source code in solc, that error is raised when it cannot fetch the appropriate compiler from github. https://github.com/ethereum/solc-js/blob/70016bce3125cdff8c7d0b0747565b77463cecf1/wrapper.js#L243

I'm still investigating exactly what the problem is though.

**Comment by zachdaniel** [comment] 2019-04-30 15:52
@chebykin I believe your issue is separate from @acravenho's, and relates to using a version that (for some reason) is not available for us to load remotely. It *should* be available at this URL: https://ethereum.github.io/solc-bin/bin/soljson-0.5.7+commit.6da8b019.js but it is not.

**Comment by zachdaniel** [comment] 2019-04-30 16:12
@chebykin in fact, the problem is actually just an issue with the version string. Add a `v` in front of your version and try again: `v0.5.7+commit.6da8b019`

**Comment by zachdaniel** [comment] 2019-05-01 20:23
@acravenho have you been able to try out using the POST endpoint? Is it possible that the issues using the API are really related to #1873?

**Comment by acravenho** [comment] 2019-05-01 21:23
@zachdaniel I have not had a chance to try out the POST endpoint. As soon as the deployment for mainnet went live I was concentrating on the failed contracts. 

The contracts in #1873 were all test manually.

**Comment by ayrat555** [comment] 2019-07-08 12:18
@acravenho is your issue resolved?

Also, I found that contracts verified using RPC API are not formatted
https://blockscout.com/eth/mainnet/address/0x3644ab79a793244abdbca44189a01756042db2e3/contracts

@vbaranov should we close this?

**Closed** 2019-10-28 16:46 UTC
Labels: api, contract verification
