### ISSUE TITLE
Can't delegate STAKE with brave browser crypto wallet

### ISSUE THREAD

**Issue by Coalperson** [poanetwork/blockscout#3546] opened 2021-01-01 17:36 UTC
When trying to delegate stake on https://blockscout.com/poa/xdai/active-pools - with the brave browser using crypto wallets, I'm getting an error telling me that meta mask needs to be updated, however, my wallet is connected and I'm not using metamask.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Don't know
* Operating System: Win 10
* Blockscout Version/branch: Don't know

### Steps to reproduce

Start brave browser, connect wallet to https://blockscout.com/poa/xdai/active-pools - connect wallet, press stake button on any pool

### Expected behaviour

Stake menu should open to delegate stake

### Actual behaviour

Message box pops up - 
Unauthorized
Please, connect to the xDai Chain.
LINK*Instructions.*LINK If you have already connected to, please update MetaMask to the latest version.

And again, I am not using metamask, but the crypto wallet built into brave browser (which is still some version of meta mask I suppose).

**Comment by varasev** [comment] 2021-01-04 13:37
Hi @Coalperson, currently only MetaMask is supported. We plan to add other wallets in the near future. As a workaround, please, try to switch to xDai Chain in your wallet and then reload Staking DApp's page.

Also, please attach here your browser's console output when you see the message box ([press F12](https://community.brave.com/t/javascript-console/6932) in the Brave Browser to open Developer tools and switch to `Console` tab).

**Comment by Coalperson** [comment] 2021-01-07 22:43
Ok, I have a screen shot or do you want me to save it? I have since moved the stake.
![Screenshot 2021-01-07 224233](https://user-images.githubusercontent.com/76847079/103953255-b2390880-5139-11eb-8e12-1f16e90951bc.png)

**Comment by vbaranov** [comment] 2021-01-14 11:46
@Coalperson I suppose you use an ancient version of Brave. You should upgrade your Brave browser to the latest version. It should resolve your issue.
I checked that issue is not reproducible in Staking Dapp with Brave _Version 1.18.78 Chromium: 87.0.4280.141_ (It is currently the latest one (https://brave.com/latest/) and embedded crypto wallet. I am closing this ticker. Please re-open it if you will experience the issue with the latest Brave version.

**Closed by vbaranov** 2021-01-14 11:46 UTC

**Comment by Coalperson** [comment] 2021-01-14 16:20
@vbaranov 
I have updated brave, I disabled the metamask extension as well in case that was confusing blockscout. I also disabled brave shields. However the issue persists. I no longer have Stake in my 'crypto wallets' wallet, but got the same message. Maybe the message is because I no longer have stake in my wallet. If that is the case though I should get a different error message though, no?

I am using the https://xdai.poanetwork.dev/ RPC with 0x64 chain ID.

![image](https://user-images.githubusercontent.com/76847079/104617713-ac847b00-5683-11eb-903f-043a94f1462c.png)
![image](https://user-images.githubusercontent.com/76847079/104617811-cde56700-5683-11eb-8243-6d147b0b98f5.png)

I have worked aroud the issue, so no big deal if you can't replicate it and it is specific to my wallet. I just thought I would let you no that it persists. Feel free to close again.

**Comment by vbaranov** [comment] 2021-01-22 11:35
@Coalperson 

> I am using the https://xdai.poanetwork.dev/ RPC with 0x64 chain ID.

The issue is with Chain ID. You need to set it in decimal instead of hexadecimal representation: 0x64 => 100. It will resolve your issue.

**Comment by Coalperson** [comment] 2021-01-22 14:18
Excellent, yes that solved the issue thanks.
