### ISSUE TITLE
no function clause matching in anonymous fn/2 in Indexer.Transform.AddressTokenBalances.reducer/2

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout#2067] opened 2019-05-30 10:00 UTC
```
2019-05-28T09:10:54.024 [error] Task #PID<0.9783.9> started from Indexer.Block.Realtime.Fetcher terminating
** (FunctionClauseError) no function clause matching in anonymous fn/2 in Indexer.Transform.AddressTokenBalances.reducer/2
    (indexer) lib/indexer/transform/address_token_balances.ex:15: anonymous fn(%{amount: #Decimal<260878000>, block_number: nil, from_address_hash: "0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be", log_index: nil, to_address_hash: "0xa1d4084de24d46a2dba3a0e8244a33dd1c846eaf", token_contract_address_hash: "0x27054b13b1b798b345b591a4d22e6562d47ea75a", token_type: "ERC-20", transaction_hash: nil}, #MapSet<[%{address_hash: "0x885c48eff5b5ce5fa0affcdd3e944edf00e2a961", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x7c5d5677cac4ed02b02c13a1f1586404a9c331b7", block_number: 7847148, token_contract_address_hash: "0x4eef32781db07a9b7d9d36bb9ba81fa08af9d3ab"}, %{address_hash: "0x4603004ecf0760c55589d69cb080f7f31b348998", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0xf50a3cfd68a00009623e1767eb696c4cc9347a7d", block_number: 7847148, token_contract_address_hash: "0x1a5f9352af8af974bfc03399e3767df6370d82e4"}, %{address_hash: "0x62a0c5bf3d2930b2c21df839266f13ab35373422", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x4b42daa60b0e5999d2949e412777b32ba9f7f24c", block_number: 7847148, token_contract_address_hash: "0xd3ebdaea9aeac98de723f640bce4aa07e2e44192"}, %{address_hash: "0xa2c0d56dc1a0f591435f491a3095d931e5a7110f", block_number: 7847148, token_contract_address_hash: "0x915044526758533dfb918eceb6e44bc21632060d"}, %{address_hash: "0x2278faff25fccaca47b75081067b8b5e691f2af6", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x0accb4c7d0770dd5be1453f725af3e68b9f8888e", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0xa6c15739ef08611d6268f15035ae5c0eb5001a1e", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x67af65ff333d87f5c2f332926ee7d7e5dc6d0c2f", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0xf7d93975e8692011ab661f00dce5a0ef2ceaaabe", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x7ffbde3b838419bdcc9ab58b755e7a1c9132c966", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0xc85bef022bbb0b57f4e0dccf3a6291343ca67bb6", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x75b553b3d42d76b812426c6cd64ee295a531db16", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0xde14e7548a46bbbf1f3f50e98a04e58c0efc60eb", block_number: 7847148, token_contract_address_hash: "0xdac17f958d2ee523a2206206994597c13d831ec7"}, %{address_hash: "0x1452b05d0f858d9663826866e6c75138262cd123", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x326cdd2958365260fbcde273f66743bc7baa9557", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x6ad405b647405314ad7f0e1194331b7c7654318d", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x82c1b1246d7ad7253a47ae1bfcdff85f5cd423fe", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0xe9c5dc55ad4e8345bd673ff71c4ec5d1807fae03", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be", block_number: 7847148, token_contract_address_hash: "0x1c4481750daa5ff521a2a7490d9981ed46465dbd"}, %{address_hash: "0x551ca98aa9a817dde8582a36809f33613c7d4a22", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be", block_number: 7847148, token_contract_address_hash: "0xced4e93198734ddaff8492d525bd258d49eb388e"}, %{address_hash: "0x124abf27e5b3957f32071494800baaa95073dd8d", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x94ef57bfbc129af9bd1118a6c432f7645ab962a7", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0xecb4c0d2ee55bc0a361f874925f67e26c86b587b", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x564286362092d8e7936f0549571a803b203aaced", block_number: 7847148, token_contract_address_hash: "0xbf2179859fc6d5bee9bf9158632dc51678a4100e"}, %{address_hash: "0x6cc5f688a315f3dc28a7781717a9a798a59fda7b", block_number: 7847148, token_contract_address_hash: "0x5e6b6d9abad9093fdc861ea1600eba1b355cd940"}, %{address_hash: "0xfbd06e1b4c77e5899ceaa69a4aee208dbb3eed3d", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x8e6cb5aca7badc6645c489e700f9199ee27d8ae6", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x3715c8ee7412773ff2ba53cba726c26e5842f7db", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0xddc3abd615cf78cf0d7b57adf1a0242dc28795b1", block_number: 7847148, token_contract_address_hash: "0x21ab6c9fac80c59d401b37cb43f81ea9dde7fe34"}, %{address_hash: "0x17ed5216703b728e73594a7e32d7fdbe5ec72735", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x4e7ee03ff4fdddec5c815feb6eb4b6822d03d02e", block_number: 7847148, token_contract_address_hash: "0x21ab6c9fac80c59d401b37cb43f81ea9dde7fe34"}, %{address_hash: "0x5c92b0cbe792970690f23bf87981d6eed63563c6", block_number: 7847148, token_contract_address_hash: "0xcf61e590ed0dd43c99155de252289079c2345f37"}, %{address_hash: "0xf0bfd2578f875e6179c9f2e8b194cb2e2b4377a0", block_number: 7847148, token_contract_address_hash: "0x5e6b6d9abad9093fdc861ea1600eba1b355cd940"}, %{address_hash: "0xc2610a25f4f058e45495e3beeebc758661ccda86", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x83bbc499096121cbb2cd7b9724b25f5dcca93ec7", block_number: 7847148, token_contract_address_hash: "0xd0352a019e9ab9d757776f532377aaebd36fd541"}, %{address_hash: "0xcf983f5bf95128d0342863e042885200be0b9866", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x77e66fd7db705924b90f5972b9dae9a2feabd65e", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x927d893e627bd1f8ce1aa19ee2c7f17ba8944119", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x119ffc2f346865678d49e7964580eedb17d18c5b", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x2823d8c9535ee071e6d3216770b159da7b10cd9c", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x96979c87783cd9cb62cf24adebec93d2b546c640", block_number: 7847148, token_contract_address_hash: "0x915044526758533dfb918eceb6e44bc21632060d"}, %{address_hash: "0xf775775d4fa85ad918a32a3489d50da8573e8261", block_number: 7847148, token_contract_address_hash: "0x174bfa6600bf90c885c7c01c7031389ed1461ab9"}, %{address_hash: "0x498fb83ec8a1b3686c8619b70bf058793637e974", block_number: 7847148, token_contract_address_hash: "0x498d99de4268cebca264887f591c4ba8fac042e4"}, %{address_hash: "0xd551234ae421e3bcba99a0da6d736074f22192ff", block_number: 7847148, ...}, %{address_hash: "0x23964aaefb1b285155390a8a5b0b434e15dbfee3", ...}, %{...}, ...]>) in Indexer.Transform.AddressTokenBalances.reducer/2
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib) maps.erl:257: :maps.fold_1/3
    (indexer) lib/indexer/block/fetcher.ex:157: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:256: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
    (indexer) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:239: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [7847148, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "XXX/", method_to_url: [eth_getBalance: "XXX", trace_block: "XXX", trace_replayTransaction: "XXX"], http_options: [recv_timeout: 1800000, timeout: 1800000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], receipts_batch_size: 250, receipts_concurrency: 10}, false]
```

**Comment by saneery** [comment] 2019-06-11 11:27
@vbaranov

Look like it's duplicate of https://github.com/poanetwork/blockscout/issues/2084. Same error

**Comment by saneery** [comment] 2019-06-11 13:20
@vbaranov Is it from mainnet? To what node it's connected?

**Closed** 2019-06-20 07:39 UTC
Labels: bug :bug:, priority: medium
